#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/backend"
ENV_FILE="${BACKEND_DIR}/.env"
PAIRING_FILE="${BACKEND_DIR}/pairing.json"
SECURITY_MODE="safe"
PAIR_CODE_TTL_MIN="30"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: ${cmd}" >&2
    exit 1
  fi
}

gen_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi
  python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
}

gen_pair_code() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(10))
PY
}

pair_code_expiry() {
  PAIR_TTL_MIN="${PAIR_CODE_TTL_MIN}" python3 - <<'PY'
from datetime import datetime, timedelta, timezone
import os
ttl = int(os.environ["PAIR_TTL_MIN"])
print((datetime.now(timezone.utc) + timedelta(minutes=ttl)).isoformat().replace("+00:00", "Z"))
PY
}

detect_url() {
  local url=""
  if command -v tailscale >/dev/null 2>&1; then
    local ts_ip
    ts_ip="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
    if [[ -n "${ts_ip}" ]]; then
      url="http://${ts_ip}:8000"
    fi
  fi
  if [[ -z "${url}" ]]; then
    url="http://127.0.0.1:8000"
  fi
  printf "%s" "${url}"
}

write_env_file() {
  local token="$1"
  local codex_unrestricted="false"
  local allow_abs_reads="false"
  if [[ "${SECURITY_MODE}" == "full-access" ]]; then
    codex_unrestricted="true"
    allow_abs_reads="true"
  fi
  if [[ -f "${ENV_FILE}" ]]; then
    echo "Keeping existing ${ENV_FILE}"
    local tmp_env
    tmp_env="$(mktemp)"
    awk \
      -v mode="${SECURITY_MODE}" \
      -v codex="${codex_unrestricted}" \
      -v reads="${allow_abs_reads}" \
      '
      BEGIN {
        seen_mode=0
        seen_codex=0
        seen_reads=0
      }
      /^VOICE_AGENT_SECURITY_MODE=/ {
        print "VOICE_AGENT_SECURITY_MODE=" mode
        seen_mode=1
        next
      }
      /^VOICE_AGENT_CODEX_UNRESTRICTED=/ {
        print "VOICE_AGENT_CODEX_UNRESTRICTED=" codex
        seen_codex=1
        next
      }
      /^VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=/ {
        print "VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=" reads
        seen_reads=1
        next
      }
      { print }
      END {
        if (!seen_mode) print "VOICE_AGENT_SECURITY_MODE=" mode
        if (!seen_codex) print "VOICE_AGENT_CODEX_UNRESTRICTED=" codex
        if (!seen_reads) print "VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=" reads
      }
      ' "${ENV_FILE}" > "${tmp_env}"
    mv "${tmp_env}" "${ENV_FILE}"
    return
  fi
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install_backend.sh
VOICE_AGENT_API_TOKEN=${token}
VOICE_AGENT_HOST=0.0.0.0
VOICE_AGENT_PORT=8000
VOICE_AGENT_SECURITY_MODE=${SECURITY_MODE}
VOICE_AGENT_CODEX_BINARY=codex
VOICE_AGENT_CODEX_UNRESTRICTED=${codex_unrestricted}
VOICE_AGENT_CODEX_GUARDRAILS=warn
VOICE_AGENT_CODEX_DANGEROUS_CONFIRM_TOKEN=[allow-dangerous]
VOICE_AGENT_CODEX_USE_CONTEXT=true
VOICE_AGENT_CODEX_CONTEXT_FILE=AGENT_CONTEXT.md
VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=${allow_abs_reads}
VOICE_AGENT_PAIR_CODE_TTL_MIN=${PAIR_CODE_TTL_MIN}
# Optional model override:
# VOICE_AGENT_CODEX_MODEL=gpt-5.1
# Transcription provider: openai (default) or mock
VOICE_AGENT_TRANSCRIBE_PROVIDER=openai
# SQLite run store path:
VOICE_AGENT_DB_PATH=data/runs.db
# Optional fixed transcript text for /v1/audio mock mode:
# VOICE_AGENT_TRANSCRIBE_MOCK_TEXT=hello from audio
# OpenAI key is required when provider=openai:
# OPENAI_API_KEY=sk-...
# Optional OpenAI transcription model when provider=openai:
# VOICE_AGENT_TRANSCRIBE_MODEL=whisper-1
EOF
  echo "Created ${ENV_FILE}"
}

main() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode)
        SECURITY_MODE="$2"
        shift 2
        ;;
      --pair-ttl-min)
        PAIR_CODE_TTL_MIN="$2"
        shift 2
        ;;
      -h|--help)
        echo "Usage: bash ./scripts/install_backend.sh [--mode safe|full-access] [--pair-ttl-min <minutes>]"
        exit 0
        ;;
      *)
        echo "Unknown argument: $1" >&2
        exit 1
        ;;
    esac
  done

  if [[ "${SECURITY_MODE}" != "safe" && "${SECURITY_MODE}" != "full-access" ]]; then
    echo "Invalid --mode '${SECURITY_MODE}'. Expected safe or full-access." >&2
    exit 1
  fi

  require_cmd python3
  require_cmd uv

  local token
  token="$(gen_token)"
  local pair_code
  pair_code="$(gen_pair_code)"
  local pair_code_expires_at
  pair_code_expires_at="$(pair_code_expiry)"
  write_env_file "${token}"

  echo "Syncing backend environment with uv..."
  (
    cd "${BACKEND_DIR}"
    uv sync
  )

  if [[ -f "${ENV_FILE}" ]]; then
    token="$(awk -F= '/^VOICE_AGENT_API_TOKEN=/{print $2}' "${ENV_FILE}")"
  fi

  local server_url
  server_url="$(detect_url)"

  cat > "${PAIRING_FILE}" <<EOF
{
  "server_url": "${server_url}",
  "api_token": "${token}",
  "session_id": "iphone-app",
  "pair_code": "${pair_code}",
  "pair_code_expires_at": "${pair_code_expires_at}"
}
EOF

  if ! command -v codex >/dev/null 2>&1; then
    echo "Warning: codex CLI not found in PATH. Install/login before using executor=codex." >&2
  fi

  echo
  echo "Backend install complete."
  echo
  echo "Start server:"
  echo "  cd \"${BACKEND_DIR}\""
  echo "  bash ./run_backend.sh"
  echo
  echo "Install always-on macOS service (recommended on Mac):"
  echo "  bash ./scripts/service_macos.sh install"
  echo
  echo "Pairing info written to:"
  echo "  ${PAIRING_FILE}"
  echo
  echo "Runtime security mode:"
  echo "  ${SECURITY_MODE}"
  echo
  echo "Use in iOS app onboarding:"
  echo "  server_url: ${server_url}"
  echo "  pair_code: ${pair_code} (expires ${pair_code_expires_at})"
  echo "  session_id: iphone-app"
  echo "  # fallback admin token: ${token}"
  echo
  echo "Generate pairing QR deep link (recommended):"
  echo "  bash ./scripts/pairing_qr.sh"
  echo "  # then scan with iPhone Camera and open in MOBaiLE"
}

main "$@"
