#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/backend"
ENV_FILE="${BACKEND_DIR}/.env"
PAIRING_FILE="${BACKEND_DIR}/pairing.json"
SECURITY_MODE="safe"
PAIR_CODE_TTL_MIN="30"
EXPOSE_NETWORK="false"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: ${cmd}" >&2
    exit 1
  fi
}

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  echo "uv not found. Installing uv..."
  require_cmd curl
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${PATH}"
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv install completed but uv is still not on PATH." >&2
    echo "Open a new shell and run again, or add ~/.local/bin to PATH." >&2
    exit 1
  fi
}

gen_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi
  python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
}

gen_pair_code() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(10))
PY
}

pair_code_expiry() {
  PAIR_TTL_MIN="${PAIR_CODE_TTL_MIN}" python3 - <<'PY'
from datetime import datetime, timedelta, timezone
import os
ttl = int(os.environ["PAIR_TTL_MIN"])
print((datetime.now(timezone.utc) + timedelta(minutes=ttl)).isoformat().replace("+00:00", "Z"))
PY
}

detect_lan_ip() {
  local ip=""

  if command -v ipconfig >/dev/null 2>&1; then
    local iface
    for iface in en0 en1 en2; do
      ip="$(ipconfig getifaddr "${iface}" 2>/dev/null || true)"
      if [[ -n "${ip}" ]]; then
        printf "%s" "${ip}"
        return
      fi
    done
  fi

  if command -v hostname >/dev/null 2>&1; then
    local candidate
    for candidate in $(hostname -I 2>/dev/null || true); do
      if [[ "${candidate}" != 127.* && "${candidate}" != "::1" ]]; then
        printf "%s" "${candidate}"
        return
      fi
    done
  fi

  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i = 1; i <= NF; i++) if ($i == "src") {print $(i + 1); exit}}')"
    if [[ -n "${ip}" && "${ip}" != 127.* ]]; then
      printf "%s" "${ip}"
      return
    fi
  fi
}

detect_url() {
  if [[ "${EXPOSE_NETWORK}" != "true" ]]; then
    printf "http://127.0.0.1:8000"
    return
  fi
  local url=""
  if command -v tailscale >/dev/null 2>&1; then
    local ts_ip
    ts_ip="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
    if [[ -n "${ts_ip}" ]]; then
      url="http://${ts_ip}:8000"
    fi
  fi
  if [[ -z "${url}" ]]; then
    local lan_ip
    lan_ip="$(detect_lan_ip)"
    if [[ -n "${lan_ip}" ]]; then
      url="http://${lan_ip}:8000"
    else
      url="http://127.0.0.1:8000"
    fi
  fi
  printf "%s" "${url}"
}

write_env_file() {
  local token="$1"
  local codex_unrestricted="false"
  local allow_abs_reads="false"
  local host_value="127.0.0.1"
  if [[ "${EXPOSE_NETWORK}" == "true" ]]; then
    host_value="0.0.0.0"
  fi
  if [[ "${SECURITY_MODE}" == "full-access" ]]; then
    codex_unrestricted="true"
    allow_abs_reads="true"
  fi
  if [[ -f "${ENV_FILE}" ]]; then
    echo "Keeping existing ${ENV_FILE}"
    local tmp_env
    tmp_env="$(mktemp)"
    awk \
      -v mode="${SECURITY_MODE}" \
      -v codex="${codex_unrestricted}" \
      -v reads="${allow_abs_reads}" \
      -v host="${host_value}" \
      '
      BEGIN {
        seen_mode=0
        seen_codex=0
        seen_reads=0
        seen_host=0
      }
      /^VOICE_AGENT_HOST=/ {
        print "VOICE_AGENT_HOST=" host
        seen_host=1
        next
      }
      /^VOICE_AGENT_SECURITY_MODE=/ {
        print "VOICE_AGENT_SECURITY_MODE=" mode
        seen_mode=1
        next
      }
      /^VOICE_AGENT_CODEX_UNRESTRICTED=/ {
        print "VOICE_AGENT_CODEX_UNRESTRICTED=" codex
        seen_codex=1
        next
      }
      /^VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=/ {
        print "VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=" reads
        seen_reads=1
        next
      }
      { print }
      END {
        if (!seen_host) print "VOICE_AGENT_HOST=" host
        if (!seen_mode) print "VOICE_AGENT_SECURITY_MODE=" mode
        if (!seen_codex) print "VOICE_AGENT_CODEX_UNRESTRICTED=" codex
        if (!seen_reads) print "VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=" reads
      }
      ' "${ENV_FILE}" > "${tmp_env}"
    mv "${tmp_env}" "${ENV_FILE}"
    return
  fi
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install_backend.sh
VOICE_AGENT_API_TOKEN=${token}
VOICE_AGENT_HOST=${host_value}
VOICE_AGENT_PORT=8000
VOICE_AGENT_SECURITY_MODE=${SECURITY_MODE}
VOICE_AGENT_DEFAULT_EXECUTOR=codex
VOICE_AGENT_CODEX_BINARY=codex
VOICE_AGENT_CODEX_UNRESTRICTED=${codex_unrestricted}
VOICE_AGENT_CODEX_GUARDRAILS=warn
VOICE_AGENT_CODEX_DANGEROUS_CONFIRM_TOKEN=[allow-dangerous]
VOICE_AGENT_CODEX_USE_CONTEXT=true
VOICE_AGENT_CODEX_CONTEXT_FILE=AGENT_CONTEXT.md
# Optional Claude Code support:
VOICE_AGENT_CLAUDE_BINARY=claude
# VOICE_AGENT_CLAUDE_MODEL=sonnet
# VOICE_AGENT_CLAUDE_PERMISSION_MODE=acceptEdits
VOICE_AGENT_ALLOW_ABSOLUTE_FILE_READS=${allow_abs_reads}
VOICE_AGENT_PAIR_CODE_TTL_MIN=${PAIR_CODE_TTL_MIN}
# Optional model override:
# VOICE_AGENT_CODEX_MODEL=gpt-5.1
# Transcription provider: openai or mock
# Set this to mock for deterministic local testing.
VOICE_AGENT_TRANSCRIBE_PROVIDER=openai
# SQLite run store path:
VOICE_AGENT_DB_PATH=data/runs.db
# Optional fixed transcript text for /v1/audio mock mode:
# VOICE_AGENT_TRANSCRIBE_MOCK_TEXT=hello from audio
# OpenAI key is required when provider=openai:
# OPENAI_API_KEY=sk-...
# Optional OpenAI transcription model when provider=openai:
# VOICE_AGENT_TRANSCRIBE_MODEL=whisper-1
EOF
  echo "Created ${ENV_FILE}"
}

main() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode)
        SECURITY_MODE="$2"
        shift 2
        ;;
      --pair-ttl-min)
        PAIR_CODE_TTL_MIN="$2"
        shift 2
        ;;
      --expose-network)
        EXPOSE_NETWORK="true"
        shift
        ;;
      -h|--help)
        echo "Usage: bash ./scripts/install_backend.sh [--mode safe|full-access] [--pair-ttl-min <minutes>] [--expose-network]"
        exit 0
        ;;
      *)
        echo "Unknown argument: $1" >&2
        exit 1
        ;;
    esac
  done

  if [[ "${SECURITY_MODE}" != "safe" && "${SECURITY_MODE}" != "full-access" ]]; then
    echo "Invalid --mode '${SECURITY_MODE}'. Expected safe or full-access." >&2
    exit 1
  fi

  require_cmd python3
  ensure_uv

  local token
  token="$(gen_token)"
  local pair_code
  pair_code="$(gen_pair_code)"
  local pair_code_expires_at
  pair_code_expires_at="$(pair_code_expiry)"
  write_env_file "${token}"

  echo "Syncing backend environment with uv..."
  (
    cd "${BACKEND_DIR}"
    uv sync
  )

  if [[ -f "${ENV_FILE}" ]]; then
    token="$(awk -F= '/^VOICE_AGENT_API_TOKEN=/{print $2}' "${ENV_FILE}")"
  fi

  local server_url
  server_url="$(detect_url)"

  cat > "${PAIRING_FILE}" <<EOF
{
  "server_url": "${server_url}",
  "api_token": "${token}",
  "session_id": "iphone-app",
  "pair_code": "${pair_code}",
  "pair_code_expires_at": "${pair_code_expires_at}"
}
EOF

  local has_codex="false"
  local has_claude="false"
  if command -v codex >/dev/null 2>&1; then
    has_codex="true"
  fi
  if command -v claude >/dev/null 2>&1; then
    has_claude="true"
  fi

  echo
  echo "Backend install complete."
  echo
  echo "Start server:"
  echo "  cd \"${BACKEND_DIR}\""
  echo "  bash ./run_backend.sh"
  echo
  echo "Install always-on service:"
  echo "  # macOS"
  echo "  bash ./scripts/service_macos.sh install"
  echo "  # Linux (systemd user service)"
  echo "  bash ./scripts/service_linux.sh install"
  echo
  echo "Pairing info written to:"
  echo "  ${PAIRING_FILE}"
  echo
  echo "Runtime security mode:"
  echo "  ${SECURITY_MODE}"
  echo "Bind host:"
  if [[ "${EXPOSE_NETWORK}" == "true" ]]; then
    echo "  0.0.0.0 (network-exposed)"
  else
    echo "  127.0.0.1 (local-only)"
  fi
  echo
  echo "Use in iOS app onboarding:"
  echo "  server_url: ${server_url}"
  echo "  pair_code: ${pair_code} (expires ${pair_code_expires_at})"
  echo "  session_id: iphone-app"
  echo "  # token is stored in backend/.env (not printed)"
  if [[ "${EXPOSE_NETWORK}" != "true" ]]; then
    echo
    echo "Remote phone access is disabled in local-only mode."
    echo "Re-run with --expose-network to pair over LAN/Tailscale."
  fi
  echo
  if [[ "${has_codex}" == "true" || "${has_claude}" == "true" ]]; then
    echo "Agent executors detected:"
    [[ "${has_codex}" == "true" ]] && echo "  codex"
    [[ "${has_claude}" == "true" ]] && echo "  claude"
  else
    echo "No Codex/Claude CLI detected. MOBaiLE will keep only the internal local smoke/dev fallback available."
  fi
  echo
  echo "Generate pairing QR deep link (recommended):"
  echo "  bash ./scripts/pairing_qr.sh"
  echo "  # then scan with iPhone Camera and open in MOBaiLE"
  if [[ "${EXPOSE_NETWORK}" == "true" && "${server_url}" == "http://127.0.0.1:8000" ]]; then
    echo
    echo "Warning: could not detect a LAN/Tailscale IP, so pairing URL still points to 127.0.0.1." >&2
    echo "Set server_url manually in the app if your machine is reachable at another address." >&2
  fi
}

main "$@"
