#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/backend"
ENV_FILE="${BACKEND_DIR}/.env"
PAIRING_FILE="${BACKEND_DIR}/pairing.json"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: ${cmd}" >&2
    exit 1
  fi
}

gen_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi
  python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
}

detect_url() {
  local url=""
  if command -v tailscale >/dev/null 2>&1; then
    local ts_ip
    ts_ip="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
    if [[ -n "${ts_ip}" ]]; then
      url="http://${ts_ip}:8000"
    fi
  fi
  if [[ -z "${url}" ]]; then
    url="http://127.0.0.1:8000"
  fi
  printf "%s" "${url}"
}

write_env_file() {
  local token="$1"
  if [[ -f "${ENV_FILE}" ]]; then
    echo "Keeping existing ${ENV_FILE}"
    return
  fi
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install_backend.sh
VOICE_AGENT_API_TOKEN=${token}
VOICE_AGENT_HOST=0.0.0.0
VOICE_AGENT_PORT=8000
VOICE_AGENT_CODEX_BINARY=codex
VOICE_AGENT_CODEX_UNRESTRICTED=true
# Optional model override:
# VOICE_AGENT_CODEX_MODEL=gpt-5.1
# Transcription provider: openai (default) or mock
VOICE_AGENT_TRANSCRIBE_PROVIDER=openai
# SQLite run store path:
VOICE_AGENT_DB_PATH=data/runs.db
# Optional fixed transcript text for /v1/audio mock mode:
# VOICE_AGENT_TRANSCRIBE_MOCK_TEXT=hello from audio
# OpenAI key is required when provider=openai:
# OPENAI_API_KEY=sk-...
# Optional OpenAI transcription model when provider=openai:
# VOICE_AGENT_TRANSCRIBE_MODEL=whisper-1
EOF
  echo "Created ${ENV_FILE}"
}

main() {
  require_cmd python3
  require_cmd uv

  local token
  token="$(gen_token)"
  write_env_file "${token}"

  echo "Syncing backend environment with uv..."
  (
    cd "${BACKEND_DIR}"
    uv sync
  )

  if [[ -f "${ENV_FILE}" ]]; then
    token="$(awk -F= '/^VOICE_AGENT_API_TOKEN=/{print $2}' "${ENV_FILE}")"
  fi

  local server_url
  server_url="$(detect_url)"

  cat > "${PAIRING_FILE}" <<EOF
{
  "server_url": "${server_url}",
  "api_token": "${token}"
}
EOF

  if ! command -v codex >/dev/null 2>&1; then
    echo "Warning: codex CLI not found in PATH. Install/login before using executor=codex." >&2
  fi

  echo
  echo "Backend install complete."
  echo
  echo "Start server:"
  echo "  cd \"${BACKEND_DIR}\""
  echo "  bash ./run_backend.sh"
  echo
  echo "Install always-on macOS service (recommended on Mac):"
  echo "  bash ./scripts/service_macos.sh install"
  echo
  echo "Pairing info written to:"
  echo "  ${PAIRING_FILE}"
  echo
  echo "Use in iOS app onboarding:"
  echo "  server_url: ${server_url}"
  echo "  api_token: ${token}"
  echo
  echo "Generate pairing QR (optional):"
  echo "  bash ./scripts/pairing_qr.sh"
}

main "$@"
